version: 2

sources:
  - name: raw
    #database: default  # Replace with your actual database name
    schema: raw # This should match the schema where your seed data is loaded
    tables:
      - name: raw_customers
      - name: raw_orders